name: CI

on:
  push:
    paths-ignore:
      - README.md
      - LICENSE.txt
    branches: [main]

  pull_request:
    types: [opened, synchronize, reopened]
    
env:
  CARGO_TERM_COLOR: always

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:    
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Bump version to beta
      uses: jacobtomlinson/gha-find-replace@v3
      with:
        find: "0.0.0-alpha"
        replace: "0.0.0-beta"
        include: "Cargo.toml"
        regex: false

    - name: Install rust
      uses: dtolnay/rust-toolchain@nightly

    - name: Cache rust
      uses: Swatinem/rust-cache@v2

    - name: Build
      run: cargo build

    - name: Run tests
      run: cargo test